# Generated by Django 3.0.5 on 2020-04-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_pip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pip',
            new_name='phone_number',
        ),
    ]
