# Generated by Django 3.0.5 on 2020-04-17 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0005_auto_20200413_1548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_1', models.TextField(default='', verbose_name='Сообщение предлагателя')),
                ('reason_for_refusal', models.TextField(default='', verbose_name='Сообщение с причиной отказа')),
                ('permission', models.BooleanField(default=None, null=True, verbose_name='Согласие')),
                ('books_of_interest_1', models.ManyToManyField(to='book.Book', verbose_name='Интересующие книги предлагателя')),
                ('books_of_interest_2', models.ManyToManyField(blank=True, db_table='BooksOfInterestToTheOfferRecipient', related_name='interest', to='book.Book', verbose_name='Интересующие книги получатель предложения')),
                ('who_offers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_offers', to=settings.AUTH_USER_MODEL, verbose_name='Предлагатель')),
                ('whomever_is_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Получатель предложения')),
            ],
        ),
    ]
