# Generated by Django 3.0.5 on 2020-04-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_1', models.TextField(blank=True, default='', verbose_name='Сообщение предлагателя')),
                ('reason_for_refusal', models.TextField(blank=True, default='', verbose_name='Сообщение с причиной отказа')),
                ('permission', models.BooleanField(default=None, null=True, verbose_name='Согласие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('books_of_interest_1', models.ManyToManyField(to='book.Book', verbose_name='Интересующие книги предлагателя')),
                ('books_of_interest_2', models.ManyToManyField(blank=True, db_table='BooksOfInterestToTheOfferRecipient', related_name='interest', to='book.Book', verbose_name='Интересующие книги получатель предложения')),
                ('who_offers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_offers', to=settings.AUTH_USER_MODEL, verbose_name='Предлагатель')),
                ('whomever_is_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Получатель предложения')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
    ]
