# Generated by Django 3.0.5 on 2020-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='message_1',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение предлагателя'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='reason_for_refusal',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение с причиной отказа'),
        ),
    ]
