# Generated by Django 3.0.5 on 2020-04-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0002_auto_20200417_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
    ]
