# Generated by Django 3.0.5 on 2020-04-24 07:55

import book.utilities.path_generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя автора')),
            ],
            options={
                'verbose_name': 'Имя автора книги',
                'verbose_name_plural': 'Имена авторов книг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BookName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя книги')),
                ('wishful', models.ManyToManyField(related_name='desired_books', to=settings.AUTH_USER_MODEL, verbose_name='Желатели книги')),
            ],
            options={
                'verbose_name': 'Имя книги',
                'verbose_name_plural': 'Имена книг',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_publishing', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('isbn', models.CharField(max_length=25, unique=True, verbose_name='ISBN')),
                ('publisging_house', models.CharField(blank=True, max_length=50, null=True, verbose_name='Издательство')),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('img', models.ImageField(blank=True, null=True, upload_to=book.utilities.path_generator.book_image_path, verbose_name='Обложка книги')),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='book.BookAuthor', verbose_name='Автор')),
                ('holders', models.ManyToManyField(related_name='my_books', to=settings.AUTH_USER_MODEL, verbose_name='Обладатели книги')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.BookName', verbose_name='Название')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_books', to='book.Section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('name', 'author'),
            },
        ),
    ]
