# Generated by Django 3.0.5 on 2020-04-13 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_auto_20200412_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='holders',
            field=models.ManyToManyField(related_name='my_book', to=settings.AUTH_USER_MODEL, verbose_name='Обладатели книги'),
        ),
        migrations.AddField(
            model_name='bookname',
            name='wishful',
            field=models.ManyToManyField(related_name='desired_books', to=settings.AUTH_USER_MODEL, verbose_name='Желатели книги'),
        ),
    ]
